### PR TITLE
Add snake case aliases for escapeURIComponent

### PR DESCRIPTION
**Pull request by casperisfine**
As agreed in [Feature #18822]

cc @nobu

### CODE REVIEW

**Comment by hsbt** [comment]
@casperisfine Sorry to late response. Can you skip tests or implement for JRuby and TruffleRuby?

**Comment by casperisfine** [comment]
@hsbt done!

**Comment by hsbt** [comment]
Thanks always!

**Comment by ioquatix** [comment]
Nice work!

**Pull request merged**
